authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import LoginView, LogoutView, UserRegistration, PasswordChangeView, PasswordResetView, \
    PasswordResetSet, PasswordResetDone
from django.contrib.auth import views as django_auth

app_name = 'authentication'
urlpatterns = [
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("signup/", UserRegistration.as_view(), name='signup'),

    #path('password_reset/done'),
# TODO: add password_change view link to profile page
    path("password_change", PasswordChangeView.as_view(), name='password-change'),

    path("password_reset/", PasswordResetView.as_view(), name='password-reset'),
    path("password_reset_set/", PasswordResetSet.as_view(), name='password-reset-set'),
    path("password_reset_done/", PasswordResetDone.as_view(), name='password-reset-done'),
]

core/urls.py
from django.urls import path
import core.views
from core.views import HomeView, PlaysView, PlayView, PerformanceView, AuthorsView, AuthorView, \
    AboutView, ActorView, DirectorView

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),

    path('plays/', PlaysView.as_view(), name='plays'),
    path('play/<int:pk>', PlayView.as_view(), name='play'),  # delete or make as buy page
    path('performance/<int:pk>', PerformanceView.as_view(), name='performance'),

    path('authors/', AuthorsView.as_view(), name='authors'),
    path('author/<int:pk>', AuthorView.as_view(), name='author'),

    #path('actors/',),
    path('actor/<int:pk>', ActorView.as_view(), name='actor'),

    path('director/<int:pk>', DirectorView.as_view(), name='director'),

]

theatre/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('authentication.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat:ital,wght@0,400;0,700;1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
{% block head %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <header class="header">
        <div class="container">
            <div class="header__inner">
                <div><a class="header__logo" href="{% url 'core:home' %}">Theatre</a></div>

                <nav class="nav">
                    <a class="nav__link" href="{% url 'core:plays' %}">Plays</a>
                    <a class="nav__link" href="{% url 'core:about' %}">Мы</a>
                    <a class="nav__link" href="#">Корзина</a>

                    {% if user.is_authenticated  %}
                        <a class="nav__link" href="#">{{ user.get_username }}</a>
                        <form method="post" class="nav__link" action="{% url 'authentication:logout' %}">
                        {% csrf_token %}
                            <button class="nav__btn" type="submit">Log Out</button>
                        </form>
                    {% else %}
                        <a class="nav__link" href="{% url 'authentication:login' %}">Log In</a>
                        <a class="nav__link" href="{% url 'authentication:signup' %}">Sign up</a>
                    {% endif %}
                </nav>
            </div>
        </div>
    </header>

    <div class="page">
        {% block content %}
        {% endblock %}
    </div>

    <!--  #TODO: footer!!!! -->
    <footer>
        Footer
    </footer>
</body>
</html>

templates/person_page.html
{% extends 'base.html' %}

{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/core/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/person.css' %}">
{% endblock %}


{% block content %}
    <section class="section">
        <div class="container">
            <div class="section__header">
                <h2 class="section__title">{% block header_title %}{% endblock %}</h2>
            </div>

            <div class="person">
                <div class="person__inner">
                    <div class="person__photo">
                        <img class="person__image" src="{% block photo_source %}{% endblock %}">
                    </div>
                    <div class="person__info">
                        <div class="person__title">{% block person_title %}{% endblock %}</div>
                        <div class="person__desc">
                            {% block description %}
                            {% endblock %}
                        </div>

                        {% if perms.editable %}
                            <div class="edit--person">
                                <form>
                                    {% csrf_token %}
                                        <button type="submit" class="btn">
                                            Edit
                                        </button>
                                        <button type="submit" class="btn">
                                            Delete
                                        </button>
                                </form>
                            </div>
                        {% endif %}

                    </div>
                    <div class="person__performances">
                        <div class="person__title">Performances</div>
                        {% block performances %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/authentication/auth.css' %}">
    {% block links %}{% endblock %}
{% endblock %}

{% block content %}
    <section class="section">
        <div class="container">
            <div class="section__title">
                <h2>{% block section_title %} {% endblock %}</h2>
            </div>

            <div class="auth">
                <div class="auth__item"></div>
                <div class="auth__item">
                   {% block form_item %}
                   {% endblock %}
                </div>
                <div class="auth__item"></div>

            </div>
        </div>
    </section>
{% endblock %}